### ISSUE TITLE
Badge: Bear Attack Survivor

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#107]
To earn: Attempt to solve a challenge more than 30 times.
Class: bronze

**Comment by butterfliege** [comment]
@QuincyLarson 

Hello :)!
This is my suggestion for the 'Bear Attack Survivor'-Badge.
Any feedback is welcome :).


![bear_attack_survivor](https://user-images.githubusercontent.com/37482829/38158026-52ec416a-348d-11e8-89da-9c20abf70f65.png)

**Comment by QuincyLarson** [comment]
@butterfliege Wow - this looks pretty cool! I'm curious what this would look like with using the Sax Mono font that we use in our logo: https://design-style-guide.freecodecamp.org/#typography

Would you be interested in making more of these?

**Comment by butterfliege** [comment]
@QuincyLarson 
I am happy you like it!
Here is the badge with the new font:

![bear_attack_survivor_saxmono](https://user-images.githubusercontent.com/37482829/38177408-4716c2f0-3601-11e8-9243-8c6cd9d5329e.png)


And yes, I am interested in making more. :D
But it will probably take some time, if that is okay?

**Comment by QuincyLarson** [comment]
@butterfliege Much better. This looks great! I'm looking forward to seeing future ones. So is the idea that the stars represent the level of the badge? Like, there might be a level 2 that's "Kraken Attack Survivor" and a Level 3 that's "Cthulu attack survivor" or something like that?

**Comment by butterfliege** [comment]
@QuincyLarson 
Yes, my idea of the star is that:
'Bear Attack Survivor' is one star, because you solved a challenge more than 30 times.
'Velociraptor Attack Survivor' would be two stars, because you solved a challenge more than 60 times.
'Shark Attack Survivor' would be three stars, because you solved a challenge more than 100 times and
'Rabbit of Caerbannog attack Survivor' would be four stars, because you solved a challenge more than 200 times..

What do you think about that? :)

**Comment by QuincyLarson** [comment]
@butterfliege Yes - that star system makes a lot of sense.

Another alternative system that may make sense would be to do a bronze (or the current freeCodeCamp Green) -> silver -> gold -> purple (or some other exotic color)

This would make it easier to glance at someone's profile and see even at a small size that they have a lot of advanced badges.
